### ISSUE TITLE
Build task has hardcoded configuration

### ISSUE THREAD

**Issue by onpremcloudguy** [1RedOne/ClientFaux#16]
Hey Stephen, 
Just attempted a build of the code and found that the post build event is coded to use: robocopy C:\git\ClientFaux\ClientFaux\bin\Debug \\DC2016\Debug & exit 0

is this still required?
Cheers
Steve

**Comment by 1RedOne** [comment]
Good find Steve, that should not be required, I'll update it.  🍺🍻
